title: Cyberspooon's Blog
description: Personal blog and technical writeups
url: "https://cyberspooon.github.io"
baseurl: ""

markdown: kramdown
theme: null

permalink: /:categories/:title/

collections:
posts:
output: true

sass:
style: compressed
