title: Cyberspooon
description: Personal blog and technical writeups
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge
theme: null

permalink: /:categories/:title/

collections:
posts:
output: true

sass:
style: compressed

plugins:
  - jekyll-feed

# Optional: hide future-dated posts locally
future: true